services:
  - type: web
    name: ffwc2026-livescore
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    plan: free
    envVars:
      - key: PORT
        value: 5001
